import Foundation

/// A single bitrate recommendation row sourced from the VideoToolbox guide.
/// Values are average target bitrates in Mbps (SDR, progressive, 4:2:0).
struct BitrateRecommendation: Identifiable {
    let id = UUID()
    let resolution: EncodeSettings.Resolution
    let highFrameRate: Bool      // false = 24–30 fps, true = 50–60 fps
    let isHEVC: Bool
    let useCase: String          // "Streaming / VOD" or "Local library"
    let content: String
    let low: Double
    let recommended: Double
    let high: Double

    /// Recommendations matching a resolution, codec, and frame-rate bucket.
    static func matching(resolution: EncodeSettings.Resolution,
                         isHEVC: Bool,
                         highFrameRate: Bool) -> [BitrateRecommendation] {
        all.filter {
            $0.resolution == resolution && $0.isHEVC == isHEVC && $0.highFrameRate == highFrameRate
        }
    }

    static let all: [BitrateRecommendation] = [
        .init(resolution: .p720, highFrameRate: false, isHEVC: false, useCase: "Streaming / VOD", content: "Animation / anime", low: 2.5, recommended: 3, high: 3.5),
        .init(resolution: .p720, highFrameRate: false, isHEVC: true, useCase: "Streaming / VOD", content: "Animation / anime", low: 1.5, recommended: 2, high: 2.5),
        .init(resolution: .p720, highFrameRate: false, isHEVC: false, useCase: "Streaming / VOD", content: "Television — studio / clean", low: 3, recommended: 3.5, high: 4.5),
        .init(resolution: .p720, highFrameRate: false, isHEVC: true, useCase: "Streaming / VOD", content: "Television — studio / clean", low: 2, recommended: 2.5, high: 3),
        .init(resolution: .p720, highFrameRate: false, isHEVC: false, useCase: "Streaming / VOD", content: "Live action — general", low: 3.5, recommended: 4.5, high: 5.5),
        .init(resolution: .p720, highFrameRate: false, isHEVC: true, useCase: "Streaming / VOD", content: "Live action — general", low: 2.5, recommended: 3, high: 3.5),
        .init(resolution: .p720, highFrameRate: false, isHEVC: false, useCase: "Streaming / VOD", content: "Movies — clean / modern", low: 5, recommended: 6, high: 7.5),
        .init(resolution: .p720, highFrameRate: false, isHEVC: true, useCase: "Streaming / VOD", content: "Movies — clean / modern", low: 3, recommended: 4, high: 5),
        .init(resolution: .p720, highFrameRate: false, isHEVC: false, useCase: "Streaming / VOD", content: "Grainy / dark / high motion", low: 7.5, recommended: 9.5, high: 11),
        .init(resolution: .p720, highFrameRate: false, isHEVC: true, useCase: "Streaming / VOD", content: "Grainy / dark / high motion", low: 5, recommended: 6, high: 7.5),
        .init(resolution: .p720, highFrameRate: false, isHEVC: false, useCase: "Local library", content: "Animation / anime", low: 3.5, recommended: 4.5, high: 5.5),
        .init(resolution: .p720, highFrameRate: false, isHEVC: true, useCase: "Local library", content: "Animation / anime", low: 2.5, recommended: 3, high: 3.5),
        .init(resolution: .p720, highFrameRate: false, isHEVC: false, useCase: "Local library", content: "Television — studio / clean", low: 5, recommended: 6, high: 7),
        .init(resolution: .p720, highFrameRate: false, isHEVC: true, useCase: "Local library", content: "Television — studio / clean", low: 3, recommended: 3.5, high: 4.5),
        .init(resolution: .p720, highFrameRate: false, isHEVC: false, useCase: "Local library", content: "Live action — general", low: 5.5, recommended: 7, high: 8),
        .init(resolution: .p720, highFrameRate: false, isHEVC: true, useCase: "Local library", content: "Live action — general", low: 3.5, recommended: 4.5, high: 5.5),
        .init(resolution: .p720, highFrameRate: false, isHEVC: false, useCase: "Local library", content: "Movies — clean / modern", low: 7.5, recommended: 9.5, high: 11),
        .init(resolution: .p720, highFrameRate: false, isHEVC: true, useCase: "Local library", content: "Movies — clean / modern", low: 5, recommended: 6, high: 7.5),
        .init(resolution: .p720, highFrameRate: false, isHEVC: false, useCase: "Local library", content: "Grainy / dark / high motion", low: 11, recommended: 14, high: 17),
        .init(resolution: .p720, highFrameRate: false, isHEVC: true, useCase: "Local library", content: "Grainy / dark / high motion", low: 7.5, recommended: 10, high: 12),
        .init(resolution: .p720, highFrameRate: true, isHEVC: false, useCase: "Streaming / VOD", content: "Animation / anime", low: 3.5, recommended: 4, high: 5),
        .init(resolution: .p720, highFrameRate: true, isHEVC: true, useCase: "Streaming / VOD", content: "Animation / anime", low: 2, recommended: 2.5, high: 3.5),
        .init(resolution: .p720, highFrameRate: true, isHEVC: false, useCase: "Streaming / VOD", content: "Television — studio / clean", low: 4.5, recommended: 5, high: 6),
        .init(resolution: .p720, highFrameRate: true, isHEVC: true, useCase: "Streaming / VOD", content: "Television — studio / clean", low: 3, recommended: 3.5, high: 4.5),
        .init(resolution: .p720, highFrameRate: true, isHEVC: false, useCase: "Streaming / VOD", content: "Live action — general", low: 5.5, recommended: 7, high: 8.5),
        .init(resolution: .p720, highFrameRate: true, isHEVC: true, useCase: "Streaming / VOD", content: "Live action — general", low: 3.5, recommended: 4.5, high: 5.5),
        .init(resolution: .p720, highFrameRate: true, isHEVC: false, useCase: "Streaming / VOD", content: "Movies — clean / modern", low: 7, recommended: 9, high: 11),
        .init(resolution: .p720, highFrameRate: true, isHEVC: true, useCase: "Streaming / VOD", content: "Movies — clean / modern", low: 4.5, recommended: 6, high: 7),
        .init(resolution: .p720, highFrameRate: true, isHEVC: false, useCase: "Streaming / VOD", content: "Grainy / dark / high motion", low: 12, recommended: 14, high: 17),
        .init(resolution: .p720, highFrameRate: true, isHEVC: true, useCase: "Streaming / VOD", content: "Grainy / dark / high motion", low: 7.5, recommended: 9.5, high: 12),
        .init(resolution: .p720, highFrameRate: true, isHEVC: false, useCase: "Local library", content: "Animation / anime", low: 5, recommended: 6.5, high: 7.5),
        .init(resolution: .p720, highFrameRate: true, isHEVC: true, useCase: "Local library", content: "Animation / anime", low: 3.5, recommended: 4, high: 5),
        .init(resolution: .p720, highFrameRate: true, isHEVC: false, useCase: "Local library", content: "Television — studio / clean", low: 7, recommended: 8, high: 9.5),
        .init(resolution: .p720, highFrameRate: true, isHEVC: true, useCase: "Local library", content: "Television — studio / clean", low: 4.5, recommended: 5, high: 6),
        .init(resolution: .p720, highFrameRate: true, isHEVC: false, useCase: "Local library", content: "Live action — general", low: 8.5, recommended: 10, high: 12),
        .init(resolution: .p720, highFrameRate: true, isHEVC: true, useCase: "Local library", content: "Live action — general", low: 5.5, recommended: 7, high: 8.5),
        .init(resolution: .p720, highFrameRate: true, isHEVC: false, useCase: "Local library", content: "Movies — clean / modern", low: 11, recommended: 13, high: 16),
        .init(resolution: .p720, highFrameRate: true, isHEVC: true, useCase: "Local library", content: "Movies — clean / modern", low: 7, recommended: 9, high: 11),
        .init(resolution: .p720, highFrameRate: true, isHEVC: false, useCase: "Local library", content: "Grainy / dark / high motion", low: 17, recommended: 22, high: 27),
        .init(resolution: .p720, highFrameRate: true, isHEVC: true, useCase: "Local library", content: "Grainy / dark / high motion", low: 12, recommended: 15, high: 19),
        .init(resolution: .p1080, highFrameRate: false, isHEVC: false, useCase: "Streaming / VOD", content: "Animation / anime", low: 4, recommended: 5, high: 6),
        .init(resolution: .p1080, highFrameRate: false, isHEVC: true, useCase: "Streaming / VOD", content: "Animation / anime", low: 2.5, recommended: 3, high: 4),
        .init(resolution: .p1080, highFrameRate: false, isHEVC: false, useCase: "Streaming / VOD", content: "Television — studio / clean", low: 5, recommended: 6, high: 7),
        .init(resolution: .p1080, highFrameRate: false, isHEVC: true, useCase: "Streaming / VOD", content: "Television — studio / clean", low: 3.5, recommended: 4, high: 5),
        .init(resolution: .p1080, highFrameRate: false, isHEVC: false, useCase: "Streaming / VOD", content: "Live action — general", low: 6, recommended: 7.5, high: 9),
        .init(resolution: .p1080, highFrameRate: false, isHEVC: true, useCase: "Streaming / VOD", content: "Live action — general", low: 4, recommended: 5, high: 6),
        .init(resolution: .p1080, highFrameRate: false, isHEVC: false, useCase: "Streaming / VOD", content: "Movies — clean / modern", low: 8, recommended: 10, high: 12),
        .init(resolution: .p1080, highFrameRate: false, isHEVC: true, useCase: "Streaming / VOD", content: "Movies — clean / modern", low: 5, recommended: 6.5, high: 8),
        .init(resolution: .p1080, highFrameRate: false, isHEVC: false, useCase: "Streaming / VOD", content: "Grainy / dark / high motion", low: 12, recommended: 15, high: 18),
        .init(resolution: .p1080, highFrameRate: false, isHEVC: true, useCase: "Streaming / VOD", content: "Grainy / dark / high motion", low: 8, recommended: 10, high: 12),
        .init(resolution: .p1080, highFrameRate: false, isHEVC: false, useCase: "Local library", content: "Animation / anime", low: 6, recommended: 7.5, high: 9),
        .init(resolution: .p1080, highFrameRate: false, isHEVC: true, useCase: "Local library", content: "Animation / anime", low: 4, recommended: 5, high: 6),
        .init(resolution: .p1080, highFrameRate: false, isHEVC: false, useCase: "Local library", content: "Television — studio / clean", low: 8, recommended: 9.5, high: 11),
        .init(resolution: .p1080, highFrameRate: false, isHEVC: true, useCase: "Local library", content: "Television — studio / clean", low: 5, recommended: 6, high: 7),
        .init(resolution: .p1080, highFrameRate: false, isHEVC: false, useCase: "Local library", content: "Live action — general", low: 9, recommended: 11, high: 13),
        .init(resolution: .p1080, highFrameRate: false, isHEVC: true, useCase: "Local library", content: "Live action — general", low: 6, recommended: 7.5, high: 9),
        .init(resolution: .p1080, highFrameRate: false, isHEVC: false, useCase: "Local library", content: "Movies — clean / modern", low: 12, recommended: 15, high: 18),
        .init(resolution: .p1080, highFrameRate: false, isHEVC: true, useCase: "Local library", content: "Movies — clean / modern", low: 8, recommended: 10, high: 12),
        .init(resolution: .p1080, highFrameRate: false, isHEVC: false, useCase: "Local library", content: "Grainy / dark / high motion", low: 18, recommended: 23, high: 28),
        .init(resolution: .p1080, highFrameRate: false, isHEVC: true, useCase: "Local library", content: "Grainy / dark / high motion", low: 12, recommended: 16, high: 20),
        .init(resolution: .p1080, highFrameRate: true, isHEVC: false, useCase: "Streaming / VOD", content: "Animation / anime", low: 5.5, recommended: 7, high: 8),
        .init(resolution: .p1080, highFrameRate: true, isHEVC: true, useCase: "Streaming / VOD", content: "Animation / anime", low: 3.5, recommended: 4.5, high: 5.5),
        .init(resolution: .p1080, highFrameRate: true, isHEVC: false, useCase: "Streaming / VOD", content: "Television — studio / clean", low: 7, recommended: 8.5, high: 10),
        .init(resolution: .p1080, highFrameRate: true, isHEVC: true, useCase: "Streaming / VOD", content: "Television — studio / clean", low: 5, recommended: 6, high: 7),
        .init(resolution: .p1080, highFrameRate: true, isHEVC: false, useCase: "Streaming / VOD", content: "Live action — general", low: 9, recommended: 11, high: 14),
        .init(resolution: .p1080, highFrameRate: true, isHEVC: true, useCase: "Streaming / VOD", content: "Live action — general", low: 6, recommended: 7.5, high: 9),
        .init(resolution: .p1080, highFrameRate: true, isHEVC: false, useCase: "Streaming / VOD", content: "Movies — clean / modern", low: 12, recommended: 14, high: 17),
        .init(resolution: .p1080, highFrameRate: true, isHEVC: true, useCase: "Streaming / VOD", content: "Movies — clean / modern", low: 7, recommended: 9.5, high: 12),
        .init(resolution: .p1080, highFrameRate: true, isHEVC: false, useCase: "Streaming / VOD", content: "Grainy / dark / high motion", low: 19, recommended: 23, high: 28),
        .init(resolution: .p1080, highFrameRate: true, isHEVC: true, useCase: "Streaming / VOD", content: "Grainy / dark / high motion", low: 12, recommended: 16, high: 19),
        .init(resolution: .p1080, highFrameRate: true, isHEVC: false, useCase: "Local library", content: "Animation / anime", low: 8, recommended: 10, high: 12),
        .init(resolution: .p1080, highFrameRate: true, isHEVC: true, useCase: "Local library", content: "Animation / anime", low: 5.5, recommended: 7, high: 8),
        .init(resolution: .p1080, highFrameRate: true, isHEVC: false, useCase: "Local library", content: "Television — studio / clean", low: 11, recommended: 13, high: 15),
        .init(resolution: .p1080, highFrameRate: true, isHEVC: true, useCase: "Local library", content: "Television — studio / clean", low: 7, recommended: 8.5, high: 10),
        .init(resolution: .p1080, highFrameRate: true, isHEVC: false, useCase: "Local library", content: "Live action — general", low: 14, recommended: 16, high: 20),
        .init(resolution: .p1080, highFrameRate: true, isHEVC: true, useCase: "Local library", content: "Live action — general", low: 9, recommended: 11, high: 14),
        .init(resolution: .p1080, highFrameRate: true, isHEVC: false, useCase: "Local library", content: "Movies — clean / modern", low: 17, recommended: 22, high: 26),
        .init(resolution: .p1080, highFrameRate: true, isHEVC: true, useCase: "Local library", content: "Movies — clean / modern", low: 12, recommended: 14, high: 17),
        .init(resolution: .p1080, highFrameRate: true, isHEVC: false, useCase: "Local library", content: "Grainy / dark / high motion", low: 28, recommended: 36, high: 43),
        .init(resolution: .p1080, highFrameRate: true, isHEVC: true, useCase: "Local library", content: "Grainy / dark / high motion", low: 19, recommended: 25, high: 31),
        .init(resolution: .k2, highFrameRate: false, isHEVC: false, useCase: "Streaming / VOD", content: "Animation / anime", low: 7, recommended: 9, high: 10),
        .init(resolution: .k2, highFrameRate: false, isHEVC: true, useCase: "Streaming / VOD", content: "Animation / anime", low: 4.5, recommended: 5.5, high: 7),
        .init(resolution: .k2, highFrameRate: false, isHEVC: false, useCase: "Streaming / VOD", content: "Television — studio / clean", low: 9, recommended: 10, high: 12),
        .init(resolution: .k2, highFrameRate: false, isHEVC: true, useCase: "Streaming / VOD", content: "Television — studio / clean", low: 6, recommended: 7.5, high: 9),
        .init(resolution: .k2, highFrameRate: false, isHEVC: false, useCase: "Streaming / VOD", content: "Live action — general", low: 10, recommended: 13, high: 16),
        .init(resolution: .k2, highFrameRate: false, isHEVC: true, useCase: "Streaming / VOD", content: "Live action — general", low: 7, recommended: 9, high: 10),
        .init(resolution: .k2, highFrameRate: false, isHEVC: false, useCase: "Streaming / VOD", content: "Movies — clean / modern", low: 14, recommended: 18, high: 21),
        .init(resolution: .k2, highFrameRate: false, isHEVC: true, useCase: "Streaming / VOD", content: "Movies — clean / modern", low: 9, recommended: 11, high: 14),
        .init(resolution: .k2, highFrameRate: false, isHEVC: false, useCase: "Streaming / VOD", content: "Grainy / dark / high motion", low: 21, recommended: 26, high: 32),
        .init(resolution: .k2, highFrameRate: false, isHEVC: true, useCase: "Streaming / VOD", content: "Grainy / dark / high motion", low: 14, recommended: 18, high: 21),
        .init(resolution: .k2, highFrameRate: false, isHEVC: false, useCase: "Local library", content: "Animation / anime", low: 10, recommended: 13, high: 16),
        .init(resolution: .k2, highFrameRate: false, isHEVC: true, useCase: "Local library", content: "Animation / anime", low: 7, recommended: 9, high: 10),
        .init(resolution: .k2, highFrameRate: false, isHEVC: false, useCase: "Local library", content: "Television — studio / clean", low: 14, recommended: 17, high: 19),
        .init(resolution: .k2, highFrameRate: false, isHEVC: true, useCase: "Local library", content: "Television — studio / clean", low: 9, recommended: 10, high: 12),
        .init(resolution: .k2, highFrameRate: false, isHEVC: false, useCase: "Local library", content: "Live action — general", low: 16, recommended: 19, high: 23),
        .init(resolution: .k2, highFrameRate: false, isHEVC: true, useCase: "Local library", content: "Live action — general", low: 10, recommended: 13, high: 16),
        .init(resolution: .k2, highFrameRate: false, isHEVC: false, useCase: "Local library", content: "Movies — clean / modern", low: 21, recommended: 26, high: 32),
        .init(resolution: .k2, highFrameRate: false, isHEVC: true, useCase: "Local library", content: "Movies — clean / modern", low: 14, recommended: 18, high: 21),
        .init(resolution: .k2, highFrameRate: false, isHEVC: false, useCase: "Local library", content: "Grainy / dark / high motion", low: 32, recommended: 40, high: 49),
        .init(resolution: .k2, highFrameRate: false, isHEVC: true, useCase: "Local library", content: "Grainy / dark / high motion", low: 21, recommended: 28, high: 35),
        .init(resolution: .k2, highFrameRate: true, isHEVC: false, useCase: "Streaming / VOD", content: "Animation / anime", low: 9.5, recommended: 12, high: 14),
        .init(resolution: .k2, highFrameRate: true, isHEVC: true, useCase: "Streaming / VOD", content: "Animation / anime", low: 6, recommended: 7.5, high: 9.5),
        .init(resolution: .k2, highFrameRate: true, isHEVC: false, useCase: "Streaming / VOD", content: "Television — studio / clean", low: 12, recommended: 15, high: 17),
        .init(resolution: .k2, highFrameRate: true, isHEVC: true, useCase: "Streaming / VOD", content: "Television — studio / clean", low: 8.5, recommended: 10, high: 12),
        .init(resolution: .k2, highFrameRate: true, isHEVC: false, useCase: "Streaming / VOD", content: "Live action — general", low: 16, recommended: 20, high: 24),
        .init(resolution: .k2, highFrameRate: true, isHEVC: true, useCase: "Streaming / VOD", content: "Live action — general", low: 10, recommended: 13, high: 16),
        .init(resolution: .k2, highFrameRate: true, isHEVC: false, useCase: "Streaming / VOD", content: "Movies — clean / modern", low: 20, recommended: 25, high: 30),
        .init(resolution: .k2, highFrameRate: true, isHEVC: true, useCase: "Streaming / VOD", content: "Movies — clean / modern", low: 13, recommended: 16, high: 20),
        .init(resolution: .k2, highFrameRate: true, isHEVC: false, useCase: "Streaming / VOD", content: "Grainy / dark / high motion", low: 33, recommended: 41, high: 49),
        .init(resolution: .k2, highFrameRate: true, isHEVC: true, useCase: "Streaming / VOD", content: "Grainy / dark / high motion", low: 22, recommended: 27, high: 33),
        .init(resolution: .k2, highFrameRate: true, isHEVC: false, useCase: "Local library", content: "Animation / anime", low: 14, recommended: 18, high: 21),
        .init(resolution: .k2, highFrameRate: true, isHEVC: true, useCase: "Local library", content: "Animation / anime", low: 9.5, recommended: 12, high: 14),
        .init(resolution: .k2, highFrameRate: true, isHEVC: false, useCase: "Local library", content: "Television — studio / clean", low: 20, recommended: 23, high: 27),
        .init(resolution: .k2, highFrameRate: true, isHEVC: true, useCase: "Local library", content: "Television — studio / clean", low: 12, recommended: 15, high: 17),
        .init(resolution: .k2, highFrameRate: true, isHEVC: false, useCase: "Local library", content: "Live action — general", low: 24, recommended: 29, high: 34),
        .init(resolution: .k2, highFrameRate: true, isHEVC: true, useCase: "Local library", content: "Live action — general", low: 16, recommended: 20, high: 24),
        .init(resolution: .k2, highFrameRate: true, isHEVC: false, useCase: "Local library", content: "Movies — clean / modern", low: 30, recommended: 38, high: 46),
        .init(resolution: .k2, highFrameRate: true, isHEVC: true, useCase: "Local library", content: "Movies — clean / modern", low: 20, recommended: 25, high: 30),
        .init(resolution: .k2, highFrameRate: true, isHEVC: false, useCase: "Local library", content: "Grainy / dark / high motion", low: 49, recommended: 60, high: 75),
        .init(resolution: .k2, highFrameRate: true, isHEVC: true, useCase: "Local library", content: "Grainy / dark / high motion", low: 33, recommended: 43, high: 55),
        .init(resolution: .k4, highFrameRate: false, isHEVC: false, useCase: "Streaming / VOD", content: "Animation / anime", low: 15, recommended: 19, high: 22),
        .init(resolution: .k4, highFrameRate: false, isHEVC: true, useCase: "Streaming / VOD", content: "Animation / anime", low: 9.5, recommended: 12, high: 15),
        .init(resolution: .k4, highFrameRate: false, isHEVC: false, useCase: "Streaming / VOD", content: "Television — studio / clean", low: 19, recommended: 22, high: 26),
        .init(resolution: .k4, highFrameRate: false, isHEVC: true, useCase: "Streaming / VOD", content: "Television — studio / clean", low: 13, recommended: 16, high: 19),
        .init(resolution: .k4, highFrameRate: false, isHEVC: false, useCase: "Streaming / VOD", content: "Live action — general", low: 22, recommended: 28, high: 34),
        .init(resolution: .k4, highFrameRate: false, isHEVC: true, useCase: "Streaming / VOD", content: "Live action — general", low: 15, recommended: 19, high: 22),
        .init(resolution: .k4, highFrameRate: false, isHEVC: false, useCase: "Streaming / VOD", content: "Movies — clean / modern", low: 30, recommended: 38, high: 45),
        .init(resolution: .k4, highFrameRate: false, isHEVC: true, useCase: "Streaming / VOD", content: "Movies — clean / modern", low: 19, recommended: 24, high: 30),
        .init(resolution: .k4, highFrameRate: false, isHEVC: false, useCase: "Streaming / VOD", content: "Grainy / dark / high motion", low: 45, recommended: 55, high: 70),
        .init(resolution: .k4, highFrameRate: false, isHEVC: true, useCase: "Streaming / VOD", content: "Grainy / dark / high motion", low: 30, recommended: 38, high: 45),
        .init(resolution: .k4, highFrameRate: false, isHEVC: false, useCase: "Local library", content: "Animation / anime", low: 22, recommended: 28, high: 34),
        .init(resolution: .k4, highFrameRate: false, isHEVC: true, useCase: "Local library", content: "Animation / anime", low: 15, recommended: 19, high: 22),
        .init(resolution: .k4, highFrameRate: false, isHEVC: false, useCase: "Local library", content: "Television — studio / clean", low: 30, recommended: 36, high: 41),
        .init(resolution: .k4, highFrameRate: false, isHEVC: true, useCase: "Local library", content: "Television — studio / clean", low: 19, recommended: 22, high: 26),
        .init(resolution: .k4, highFrameRate: false, isHEVC: false, useCase: "Local library", content: "Live action — general", low: 34, recommended: 41, high: 49),
        .init(resolution: .k4, highFrameRate: false, isHEVC: true, useCase: "Local library", content: "Live action — general", low: 22, recommended: 28, high: 34),
        .init(resolution: .k4, highFrameRate: false, isHEVC: false, useCase: "Local library", content: "Movies — clean / modern", low: 45, recommended: 55, high: 70),
        .init(resolution: .k4, highFrameRate: false, isHEVC: true, useCase: "Local library", content: "Movies — clean / modern", low: 30, recommended: 38, high: 45),
        .init(resolution: .k4, highFrameRate: false, isHEVC: false, useCase: "Local library", content: "Grainy / dark / high motion", low: 70, recommended: 85, high: 105),
        .init(resolution: .k4, highFrameRate: false, isHEVC: true, useCase: "Local library", content: "Grainy / dark / high motion", low: 45, recommended: 60, high: 75),
        .init(resolution: .k4, highFrameRate: true, isHEVC: false, useCase: "Streaming / VOD", content: "Animation / anime", low: 20, recommended: 25, high: 30),
        .init(resolution: .k4, highFrameRate: true, isHEVC: true, useCase: "Streaming / VOD", content: "Animation / anime", low: 13, recommended: 16, high: 20),
        .init(resolution: .k4, highFrameRate: true, isHEVC: false, useCase: "Streaming / VOD", content: "Television — studio / clean", low: 26, recommended: 31, high: 37),
        .init(resolution: .k4, highFrameRate: true, isHEVC: true, useCase: "Streaming / VOD", content: "Television — studio / clean", low: 18, recommended: 22, high: 26),
        .init(resolution: .k4, highFrameRate: true, isHEVC: false, useCase: "Streaming / VOD", content: "Live action — general", low: 34, recommended: 42, high: 50),
        .init(resolution: .k4, highFrameRate: true, isHEVC: true, useCase: "Streaming / VOD", content: "Live action — general", low: 22, recommended: 28, high: 34),
        .init(resolution: .k4, highFrameRate: true, isHEVC: false, useCase: "Streaming / VOD", content: "Movies — clean / modern", low: 44, recommended: 55, high: 65),
        .init(resolution: .k4, highFrameRate: true, isHEVC: true, useCase: "Streaming / VOD", content: "Movies — clean / modern", low: 27, recommended: 35, high: 44),
        .init(resolution: .k4, highFrameRate: true, isHEVC: false, useCase: "Streaming / VOD", content: "Grainy / dark / high motion", low: 70, recommended: 85, high: 105),
        .init(resolution: .k4, highFrameRate: true, isHEVC: true, useCase: "Streaming / VOD", content: "Grainy / dark / high motion", low: 46, recommended: 60, high: 70),
        .init(resolution: .k4, highFrameRate: true, isHEVC: false, useCase: "Local library", content: "Animation / anime", low: 30, recommended: 38, high: 46),
        .init(resolution: .k4, highFrameRate: true, isHEVC: true, useCase: "Local library", content: "Animation / anime", low: 20, recommended: 25, high: 30),
        .init(resolution: .k4, highFrameRate: true, isHEVC: false, useCase: "Local library", content: "Television — studio / clean", low: 42, recommended: 50, high: 60),
        .init(resolution: .k4, highFrameRate: true, isHEVC: true, useCase: "Local library", content: "Television — studio / clean", low: 26, recommended: 31, high: 37),
        .init(resolution: .k4, highFrameRate: true, isHEVC: false, useCase: "Local library", content: "Live action — general", low: 50, recommended: 60, high: 75),
        .init(resolution: .k4, highFrameRate: true, isHEVC: true, useCase: "Local library", content: "Live action — general", low: 34, recommended: 42, high: 50),
        .init(resolution: .k4, highFrameRate: true, isHEVC: false, useCase: "Local library", content: "Movies — clean / modern", low: 65, recommended: 80, high: 100),
        .init(resolution: .k4, highFrameRate: true, isHEVC: true, useCase: "Local library", content: "Movies — clean / modern", low: 44, recommended: 55, high: 65),
        .init(resolution: .k4, highFrameRate: true, isHEVC: false, useCase: "Local library", content: "Grainy / dark / high motion", low: 105, recommended: 135, high: 165),
        .init(resolution: .k4, highFrameRate: true, isHEVC: true, useCase: "Local library", content: "Grainy / dark / high motion", low: 70, recommended: 95, high: 115),
        .init(resolution: .k8, highFrameRate: false, isHEVC: false, useCase: "Streaming / VOD", content: "Animation / anime", low: 42, recommended: 50, high: 65),
        .init(resolution: .k8, highFrameRate: false, isHEVC: true, useCase: "Streaming / VOD", content: "Animation / anime", low: 26, recommended: 34, high: 42),
        .init(resolution: .k8, highFrameRate: false, isHEVC: false, useCase: "Streaming / VOD", content: "Television — studio / clean", low: 50, recommended: 65, high: 75),
        .init(resolution: .k8, highFrameRate: false, isHEVC: true, useCase: "Streaming / VOD", content: "Television — studio / clean", low: 37, recommended: 45, high: 50),
        .init(resolution: .k8, highFrameRate: false, isHEVC: false, useCase: "Streaming / VOD", content: "Live action — general", low: 65, recommended: 80, high: 95),
        .init(resolution: .k8, highFrameRate: false, isHEVC: true, useCase: "Streaming / VOD", content: "Live action — general", low: 42, recommended: 50, high: 65),
        .init(resolution: .k8, highFrameRate: false, isHEVC: false, useCase: "Streaming / VOD", content: "Movies — clean / modern", low: 85, recommended: 105, high: 125),
        .init(resolution: .k8, highFrameRate: false, isHEVC: true, useCase: "Streaming / VOD", content: "Movies — clean / modern", low: 50, recommended: 70, high: 85),
        .init(resolution: .k8, highFrameRate: false, isHEVC: false, useCase: "Streaming / VOD", content: "Grainy / dark / high motion", low: 125, recommended: 160, high: 190),
        .init(resolution: .k8, highFrameRate: false, isHEVC: true, useCase: "Streaming / VOD", content: "Grainy / dark / high motion", low: 85, recommended: 105, high: 125),
        .init(resolution: .k8, highFrameRate: false, isHEVC: false, useCase: "Local library", content: "Animation / anime", low: 65, recommended: 80, high: 95),
        .init(resolution: .k8, highFrameRate: false, isHEVC: true, useCase: "Local library", content: "Animation / anime", low: 42, recommended: 50, high: 65),
        .init(resolution: .k8, highFrameRate: false, isHEVC: false, useCase: "Local library", content: "Television — studio / clean", low: 85, recommended: 100, high: 115),
        .init(resolution: .k8, highFrameRate: false, isHEVC: true, useCase: "Local library", content: "Television — studio / clean", low: 50, recommended: 65, high: 75),
        .init(resolution: .k8, highFrameRate: false, isHEVC: false, useCase: "Local library", content: "Live action — general", low: 95, recommended: 115, high: 135),
        .init(resolution: .k8, highFrameRate: false, isHEVC: true, useCase: "Local library", content: "Live action — general", low: 65, recommended: 80, high: 95),
        .init(resolution: .k8, highFrameRate: false, isHEVC: false, useCase: "Local library", content: "Movies — clean / modern", low: 125, recommended: 160, high: 190),
        .init(resolution: .k8, highFrameRate: false, isHEVC: true, useCase: "Local library", content: "Movies — clean / modern", low: 85, recommended: 105, high: 125),
        .init(resolution: .k8, highFrameRate: false, isHEVC: false, useCase: "Local library", content: "Grainy / dark / high motion", low: 190, recommended: 240, high: 295),
        .init(resolution: .k8, highFrameRate: false, isHEVC: true, useCase: "Local library", content: "Grainy / dark / high motion", low: 125, recommended: 170, high: 210),
        .init(resolution: .k8, highFrameRate: true, isHEVC: false, useCase: "Streaming / VOD", content: "Animation / anime", low: 55, recommended: 70, high: 85),
        .init(resolution: .k8, highFrameRate: true, isHEVC: true, useCase: "Streaming / VOD", content: "Animation / anime", low: 35, recommended: 46, high: 55),
        .init(resolution: .k8, highFrameRate: true, isHEVC: false, useCase: "Streaming / VOD", content: "Television — studio / clean", low: 75, recommended: 90, high: 105),
        .init(resolution: .k8, highFrameRate: true, isHEVC: true, useCase: "Streaming / VOD", content: "Television — studio / clean", low: 50, recommended: 60, high: 75),
        .init(resolution: .k8, highFrameRate: true, isHEVC: false, useCase: "Streaming / VOD", content: "Live action — general", low: 95, recommended: 120, high: 140),
        .init(resolution: .k8, highFrameRate: true, isHEVC: true, useCase: "Streaming / VOD", content: "Live action — general", low: 65, recommended: 80, high: 95),
        .init(resolution: .k8, highFrameRate: true, isHEVC: false, useCase: "Streaming / VOD", content: "Movies — clean / modern", low: 120, recommended: 150, high: 185),
        .init(resolution: .k8, highFrameRate: true, isHEVC: true, useCase: "Streaming / VOD", content: "Movies — clean / modern", low: 75, recommended: 100, high: 120),
        .init(resolution: .k8, highFrameRate: true, isHEVC: false, useCase: "Streaming / VOD", content: "Grainy / dark / high motion", low: 195, recommended: 245, high: 295),
        .init(resolution: .k8, highFrameRate: true, isHEVC: true, useCase: "Streaming / VOD", content: "Grainy / dark / high motion", low: 130, recommended: 165, high: 195),
        .init(resolution: .k8, highFrameRate: true, isHEVC: false, useCase: "Local library", content: "Animation / anime", low: 85, recommended: 105, high: 130),
        .init(resolution: .k8, highFrameRate: true, isHEVC: true, useCase: "Local library", content: "Animation / anime", low: 55, recommended: 70, high: 85),
        .init(resolution: .k8, highFrameRate: true, isHEVC: false, useCase: "Local library", content: "Television — studio / clean", low: 120, recommended: 140, high: 160),
        .init(resolution: .k8, highFrameRate: true, isHEVC: true, useCase: "Local library", content: "Television — studio / clean", low: 75, recommended: 90, high: 105),
        .init(resolution: .k8, highFrameRate: true, isHEVC: false, useCase: "Local library", content: "Live action — general", low: 140, recommended: 175, high: 205),
        .init(resolution: .k8, highFrameRate: true, isHEVC: true, useCase: "Local library", content: "Live action — general", low: 95, recommended: 120, high: 140),
        .init(resolution: .k8, highFrameRate: true, isHEVC: false, useCase: "Local library", content: "Movies — clean / modern", low: 185, recommended: 230, high: 275),
        .init(resolution: .k8, highFrameRate: true, isHEVC: true, useCase: "Local library", content: "Movies — clean / modern", low: 120, recommended: 150, high: 185),
        .init(resolution: .k8, highFrameRate: true, isHEVC: false, useCase: "Local library", content: "Grainy / dark / high motion", low: 295, recommended: 375, high: 455),
        .init(resolution: .k8, highFrameRate: true, isHEVC: true, useCase: "Local library", content: "Grainy / dark / high motion", low: 195, recommended: 260, high: 325),
    ]
}
